name: Deploy Main Site on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v4
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude='.git/**' --exclude='.github/**'      --exclude='README.md' --exclude='.vscode/**'
          path: .
          remote_path: ${{ secrets.REMOTE_TARGET_DEMO }}
          remote_host: ${{ secrets.REMOTE_HOST_DEMO }}
          remote_port: ${{ secrets.REMOTE_PORT_DEMO }}
          remote_user: ${{ secrets.REMOTE_USER_DEMO }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY_DEMO }}
